Add initial README.md file for Travel Tracker App
josh-everett01/travel_tracker pull request #16
Opened 2020-08-12 23:41 UTC by josh-everett01

## Changes proposed by this PR
closes #8 

## What did you struggle on to complete?
Making sure formatting was correct and also making sure I was adding the correct information

## Checklist:
- [x] code has been linted with ESLint
- [x] I have reviewed my code
- [x] all issue criteria is completed 
- [x] I have fully styled all changes

## Helpful Resources:
[link_1](https://example_resource.com)
[link_2](https://example_resource_2.com)

2020-08-19 03:26 UTC, Mycobee commented on src/README.md
> +### Schema
remove

2020-08-19 03:27 UTC, Mycobee commented on src/README.md
> +### Endpoints
Remove this whole section (all endpoints)

2020-08-19 03:28 UTC, Mycobee commented on src/README.md
> +Travel Tracker is an application which manages and tracks different trips for
Say something like 
Travel tracker is an app that manages and tracks different trips for users and travel agents, by consuming and posting to an external API

2020-09-08 23:54 UTC, Mycobee requested changes
Looks good @josh-everett01 

A couple very small changes and this is good to merge.

2020-09-08 23:54 UTC, Mycobee commented on src/README.md
> +$ cd calorie_counts
`cd calorie_counts`? :)

2020-09-08 23:54 UTC, Mycobee commented on src/README.md
> +for that user
Add some markdown formatting for these lines, perhaps h4s and bulleted lists?
https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet

2020-09-15 23:16 UTC, josh-everett01 reviewed
complete

2020-09-16 14:32 UTC, Mycobee approved these changes

2020-09-16 22:24 UTC, merged